name: ClusterFuzzLite batch

on:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:

permissions: read-all

jobs:
  fuzz:
    name: Batch fuzzing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address]
    steps:
      - name: Build fuzzers
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: jvm
          sanitizer: ${{ matrix.sanitizer }}

      - name: Run fuzzers
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 600
          mode: batch
          sanitizer: ${{ matrix.sanitizer }}
          output-sarif: true
